# Generated by Django 2.0 on 2019-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190205_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
